server:
    port: 8083
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        min-response-size: 1024

spring:
    devtools:
        restart:
            enabled: true
    datasource:
        url: jdbc:mysql://10.130.210.115:3306/mnt?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        username: mnt
        password: Cloud@123
    main:
        banner-mode: "console" #在console中输出自定义字符

#flyway配置。版本号的数字间以下划线_分隔开，版本号与描述间以连续的两个下划线__分隔开。如V2_1__cus_init.sql
flyway:
    enabled: true    #flyway开关,默认为true,开发时可先设置为false

eureka:
    instance:
        appname: dataVis
        instanceId: dataVis:${spring.application.instance-id:${random.value}}
        prefer-ip-address: true
        lease-renewal-interval-in-seconds: 5
        lease-expiration-duration-in-seconds: 10
    client:
        service-url:
            defaultZone: http://admin:admin@10.130.210.115:8761/eureka/
        ## 关闭心跳检测
        registerWithEureka: true
        fetchRegistry: true

#zabbix的jdbc配置参数
jdbc_zabbix:
  url: jdbc:mysql://10.130.211.239:3306/zabbix?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false
  username: zabbix
  password: 77SHIbian01
  driver_class_name: com.mysql.jdbc.Driver

#天气预报数据抓取，city_ids'&'是分隔符
weather_url: http://10.130.151.79:8080/weather-server/weather/getData
city_ids: beijing-54511&wuhan-57494

#cmdb配置参数
cmdb: 
  host_cmdb: cmdb.easyops-only.com
  host_tool: tool.easyops-only.com
  org: 1045
  user: easyops
  url: http://10.130.213.80
  skey: P@ssw0rdP@ssw0rd
  ivparameter: 1234567890123456
