spring:
    application:
        name: datav
    profiles:
        active: test
    devtools:
        restart:
            enabled: true

ribbon:
    ReadTimeout: 60000
    ConnectTimeout: 60000

zuul: # 配置值需要根据运行情况做进一步的调整
    host:
        max-total-connections: 1000
        max-per-route-connections: 100
    semaphore:
        max-semaphores: 500

server:
    session:
        cookie:
            http-only: true

# 所有支持类的 Rest 访问统一到 admin 路径下。
management:
    context-path: /admin
    security:
        enabled: false
        roles: SUPERUSER #超级用户

#日志
logging:
    level:
        com.taikang: DEBUG
    config: classpath:config/logback-spring.xml

#flyway配置。版本号的数字间以下划线_分隔开，版本号与描述间以连续的两个下划线__分隔开。如V2_1__cus_init.sql
flyway:
    enabled: false    #flyway开关,默认为true,开发时可先设置为false

# 分页配置
pagehelper:
    #数据库类型，可选值为oracle,mysql,mariadb,sqlite,hsqldb,postgresql,sqlserver,没有默认值，必须指定该属性。
    helper-dialect: mysql
    #分页参数合理化，默认false禁用
    #启用合理化时，如果pageNum < 1会查询第一页，如果pageNum>pages会查询最后一页
    #禁用合理化时，如果pageNum<1或pageNum>pages会返回空数据
    reasonable: true
    #默认值false，分页插件会从查询方法的参数值中，自动根据params 配置的字段中取值，查找到合适的值时就会自动分页。
    support-methods-arguments: true
    #params：用于从对象中根据属性名取值，可以配置 pageNum,pageSize,count,pageSizeZero,reasonable
    #不配置映射的用默认值，默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
    params: count=countSql

cmdb:
  clusters_api: /object/APP/instance/_search
  tool_api: /tools/execution

mybatis:
    mapper-locations: classpath:mapper/*.xml
    typeAliasesPackage: com.taikang.dataVis.domain
    configuration:
        mapUnderscoreToCamelCase: true # 下划线转驼峰